sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1    

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in lithe-camp-253300-220ca752985d.json.enc -out lithe-camp-253300-220ca752985d.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file lithe-camp-253300-220ca752985d.json
  - gcloud config set project lithe-camp-253300
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jsaurabh95/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run -e CI=true jsaurabh95/react-test npm run test 

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
  